### ISSUE TITLE
Support alternative database names

### ISSUE THREAD

**Issue by gashalot** [newrelic/nri-postgresql#20]
##### Description of the problem
The current implementation does not support collection of table statistics for alternative database names other than the default `postgres` database.

I first detected this issue when the agent was unable to connect to the local database after granting `CONNECT`, the relevant permissions in [the documentation](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration), and verifying that the select statements for the required statistic tables were working as expected.

The bug can be tracked to a few problems in the implementation where the database name is hardcoded in at least two places when establishing the connection in `pgsql_connection.go` [in the defaults](https://github.com/newrelic/nri-postgresql/blob/eec89529f16bad3d309a876bc124cc10faf84110/src/connection/pgsql_connection.go#L43).

Even though `postgres` is not specified in the `collection_list` as a database, the agent attempts to connect to this database, and throws this error:

`[ERR] Metrics collection failed: error creating connection to SQL Server: pq: permission denied for database "postgres"`

This will only affect table and index statistics, as the database-level statistics can be gathered from any database on the same system, however the [query used to collect table data](https://github.com/newrelic/nri-postgresql/blob/eec89529f16bad3d309a876bc124cc10faf84110/src/metrics/table_definitions.go#L42) only returns tables within the database you connected to. You can verify this by running `SELECT * FROM pg_statio_user_tables` on a multi-database system.

Since the configuration allows specification of multiple databases in the `collection_list` JSON blob, it may be simpler to connect once for each individual database in the configuration, avoiding the need to configure a separate database parameter in the main YML file, and allowing a single agent to collect stats from multiple databases on the same PostgreSQL instance. This will also remove the implicit dependency on `CONNECT` privileges on the `postgres` database.

##### OS
This issue was first identified on a system running Debian Stretch (9.7) with PostgreSQL 11.1, nri-postgresql 1.0.1-1 (from official New Relic repository), and newrelic-infra 1.2.6.

- [x] All of them
- [x] Amazon Linux, all versions
- [x] CentOS, version 6 or higher
- [x] Debian, version 7 ("Wheezy") or higher
- [x] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [x] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [x] Windows Server, 2008 and 2012 and their service packs

**Comment by cpheps** [comment]
I think this is a fair change, adding an optional configuration parameter to specify the database. We choose the `postgres` database since it is guaranteed to be in every customers environment. We'll put it in our backlook.

**Comment by gashalot** [comment]
I'd suggest this is a bug, as your documentation implies you can monitor objects across multiple databases in `collection_list`, when this is not the case. As currently implemented, users who have >1 database name can't use your plugin for anything more than aggregate IO statistics.

**Comment by cpheps** [comment]
Ah I misinterpreted the original bug. So we only collect Table and Schema metrics for the database we currently connect to which makes sense with how it's currently implemented but not desired behavior.
