### ISSUE TITLE
[FEATURE] postgres remote monitor

### ISSUE THREAD

**Issue by keur** [newrelic/nri-postgresql#38]
##### Description of the problem

The apache, nginx, mysql and other newrelic integrations allow users to specify the agent as a remote monitor so the hostname reflects that of the postgres host rather than the infra host. Right now I have a leader and follow postgres instance and i want to discriminate between the two in newrelic insights, while keeping the sample data for each of these databases completely separate.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by camdencheek** [comment]
Hi @keur  -- thanks for the request. I don't see any reason it should be a problem to add support fo this. I'll try to get this prioritized in the next round of updates

**Comment by davidgit** [comment]
We appreciate you taking the time to bring this to our attention. After reviewing this issue, we are unable to commit on a timeline to resolution for more than a year. When committing to resolve an issue, we take into account the type of issue, the customer impact, and the development effort required. If the situation changes, we will revisit this decision.
