### ISSUE TITLE
Nri-Postgres - New metric (Max. connections)

### ISSUE THREAD

**Issue by mangulonr** [newrelic/nri-postgresql#55]
The customer need PostgreSQL integration to capture max connections so they can compute the percent connections used. Currently there is only db.connections.

[Feature request](https://newrelic.aha.io/ideas/ideas/INFSERV-I-170)

[Zendesk tickets](https://newrelic.zendesk.com/agent/tickets/452233)

**Comment by carlossscastro** [comment]
- [ ] Update documentation with new metric
