### ISSUE TITLE
Service Check 

### ISSUE THREAD

**Issue by chris-molinas** [newrelic/nri-postgresql#68]
Hi all,

One of our clients is asking if the  pgbouncer.can_connect metric is available in New Relic like it is in DataDog.  I know that this is a service check in DataDog, checking to see if PGBouncer is sending metrics.  We could probably setup an alert or something on the New Relic side that does like a count on PgBouncerSample then alert if its 0 over a certain amount of time to mirror that, correct?  Is that the correct approach or is there another approach that we should use?

Thanks

**Comment by alvarocabanas** [comment]
Hello @chris-molinas, yes, what you propose with the alert is the way to go. An instance that is configured to get the data from PGBouncer will not produce any PgBouncerSample if it fails. I think that always emitting a metric called can_connect to say if it worked or not, doesn't give any added value, and can be detected with your proposed approach.
