### ISSUE TITLE
Enable option to connect without SSL from installation wizard

### ISSUE THREAD

**Issue by zambetpentru** [newrelic/nri-postgresql#74]
Hi,

I would like to request that connection without SSL is made an option in the New Relic guided installer as it is not obvious to a new user why they can't connect with the correct username and password.

**Comment by alvarocabanas** [comment]
Hi ,
The next best step is to visit New Relic Support, where you can engage the[ New Relic Support Community](https://support.newrelic.com/) or open a support ticket depending on your support level. The support team is best positioned to assist with your specific needs.
Please provide a link to this GitHub issue when submitting your community post or support ticket.
Thanks!
