### ISSUE TITLE
Not able to connect to postgres-open-source-integration

### ISSUE THREAD

**Issue by sacoefrancis** [newrelic/nri-postgresql#75]
Hi Guys,

tried connecting postgresql with newrelic  using below command and tried manuall installation too

curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=
 NEW_RELIC_ACCOUNT_ID=
 NEW_RELIC_REGION=EU /usr/local/bin/newrelic install -n postgres-open-source-integration

error logs:

ERROR Could not find recipe with name postgres-open-source-integration. 

We encountered an issue during the installation: no recipes were installed.
For more information about about what happened, rerun the command using the --debug flag.

  newrelic install --debug 

If this problem persists, visit the documentation and support page for additional help here at https://one.newrelic.com/-/06vjAeZLKjP.

[root@tools-database integrations.d]# newrelic install --debug
DEBUG could not load string value for key region, returning zero value: no value found at path *.region 
DEBUG could not load string value for key insightsInsertKey and profile , returning zero value: no value found at path insightsInsertKey 
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
DEBUG performing request                            method=POST url="https://api.newrelic.com/graphql"
^[[BFATAL could not fetch license key for account 1234: 403 response returned

Tried manual installation in this 

https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/postgresql-monitoring-integration/#config

can you please help me in this

**Comment by sacoefrancis** [comment]
Hi @alvarocabanas  we are using oracle linux !! so hope its not supported

**Comment by alvarocabanas** [comment]
Yes, right now we don't support installing the integration through the guided install for Oracle Linux, but you can set it up through the manual install, following the instructions from here: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/.
