### ISSUE TITLE
Improve sqlx query marshaling

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-postgresql#79]
With current solution, when a version of mongodb/pgbouncer adds a new metric, when sqlx returns it and tries to marsal it to the defined struct throws an error "missing destination name three in *[]struct". Updating the code with the new struct field is the only solution.

- Adding extra returned rows in the Test_PGSQLConnection_Query it can be reproduced.

Study if this could be solved with a better more flexible approach. (reflection?)

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
